name: Build, Test and Report
on:
  push:
  schedule:
      - cron: '0 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: ncc build -o build/lib ./index.js && npx pkg index.js -t node14-linux-x64,node14-win-x64,node14-macos-x64 --out-path dist/
      - run: ./dist/index-linux # index-linux, index-macos, index-win.exe