name: Run index.js
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: node index.js
      - run: node daily-email.js