name: Send a Daily Email
on:
  schedule:
    - cron: '0 */24 * * *'
jobs:
  send-email:
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: node daily-email.js